name: Build and deploy

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set current time
        run: echo "CURRENT_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Pack everything
        run: |
          cd src
          zip -r ../src-${{ env.CURRENT_TIME }}.zip *
          cd ..
          aws s3 cp src-${{ env.CURRENT_TIME }}.zip s3://code.mlesniak.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json

      # Clear base path, since it's managed outside the template
      - name: Remove base path if possible
        continue-on-error: true
        run: |
          aws apigateway delete-base-path-mapping --domain-name dev.mlesniak.com --base-path "demo"

      # Forces redeployment of the lambda as well
      - name: Update stack
        run: |
          aws cloudformation update-stack \
            --stack-name demo \
            --template-body file://lambda.yaml \
            --parameters ParameterKey=LambdaCodeVersion,ParameterValue=${{ env.CURRENT_TIME }} \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json

      # Create base path to our custom domain
      - name: Create base path
        run: |
          aws apigateway create-base-path-mapping \
            --domain-name dev.mlesniak.com \
            --rest-api-id om8w6g3evh \
            --stage prod \
            --base-path "demo"
          
